# -*- coding: utf-8 -*-
"""WorldBankEDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CKml-xNlQjMDllkegyqj6gxLnDV5Yn-u

#**<u>World Bank Global Education Analysis</u>**

The World Bank EdStats All Indicator Query holds over 4,000 internationally comparable indicators that describe education access, progression, completion, literacy, teachers, population, and expenditures.The indicators cover the education cycle from pre-primary to vocational and tertiary education and also holds learning outcome data from international and regional learning assessments (e.g. PISA, TIMSS, PIRLS), equity data from household surveys, and projection/attainment data.

In this project we are going to analyze the EdStats Data in order to find out valuable insights

Now, The first step would be to mount the drive in order to extract the Datasets present in the Drive folder.
"""

# Mounting the Google Drive to access data.
from google.colab import drive
drive.mount('/content/drive')

"""**Importing Necessary Modules and Libraries**

We are importing following libraries for their respective applications:


*   Pandas:- Pandas is used to analyze data. It has functions for analyzing, cleaning, exploring, and manipulating data.
*   Matplotlib:- Matplotlib is a graph plotting library in python that serves as a visualization utility. Most of the Matplotlib utilities lies under the pyplot submodule.


"""

# Importing packages like pandas, matplotlib and math for analysis, visualization and arithematical operations.
import pandas as pd
import matplotlib.pyplot as plt
import math

"""###**⚖ Loading Data from Drive ⚖**

Now, we need to load our data from the external source, which in this case is uploaded to the drive. The data is divided into 5 different CSV files, each containing the information as follows:


1.   **EdStatsData**:- This file contains Education Statistics data (from year 1970 to 2100) of all the countries that are World Bank members and this data is dependent on various indicators that resembles various factors that affect the overall Education growth and development of the country. These indicators can be access, availabilty, teachers, expenditures, population, lieracy, assessments etc. 
"""

# The variable Data_path contains the path of datasets stored in a particular location in drive. 
# This path is common for all files so can be used multiple times using the Data_path variable.
Data_path = "/content/drive/MyDrive/Colab Notebooks/Almabetter/Capstone Projects/World Bank Global Education Analysis/data/"

# Importing EdStatsData File.
EdStatsData = pd.read_csv(Data_path + "EdStatsData.csv")
EdStatsData.head(3)

EdStatsData.describe()

"""2.   **EdStatsCountry**:- 

"""

EdStatsCountry = pd.read_csv(Data_path + "EdStatsCountry.csv")
EdStatsCountry.head(3)

EdStatsCountry.columns

"""3.   **EdStatsCountry-Series**:-


"""

EdStatsCountry_Series = pd.read_csv(Data_path + "EdStatsCountry-Series.csv")
EdStatsCountry_Series.head(3)



"""4.   **EdStatsFootNode**:-

"""

EdStatsFootNote = pd.read_csv(Data_path + "EdStatsFootNote.csv")
EdStatsFootNote.head(3)



"""5.   **EdStatsSeries**:-"""

EdStatsSeries = pd.read_csv(Data_path + "EdStatsSeries.csv")
EdStatsSeries.head(3)



